# Generated by Django 4.2.9 on 2024-01-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_users_email_remove_users_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_from_users',
            new_name='user_from_users_id',
        ),
    ]
