# Generated by Django 4.2.9 on 2024-01-24 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_users_is_active_alter_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_from_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.users'),
        ),
    ]
